[package]
name = "pertubation_propagator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
all_asserts = "2.3.1"
dotenv = "0.15.0"
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
ode_solvers = "0.3.7"
